### ISSUE TITLE
Write first few levels of each target area

### ISSUE THREAD

**Issue by zspencer** [codeunion/javascript-exercises#1]
## Syntax and Idioms
- [ ] Z- Level 1 - Functions and Variables (defining and calling)
- [ ] Z - Level 2 - Crab Claws `{ }`, Hugs `( )`, and Full Stops `;`
- [x] T - Level 3 - Embedding JavaScript in a Web Page - #6 
- [ ] T - Level 4 - Running JavaScript in your Browser Console
## Algorithms and Computer Science
- [x] Level 1 - Letters and Words
- [ ] Z -  Level 2 - Numbers!
- [ ] Z - Level 3 - Making Decisions and Repeating Yourself (ifs and fors)
- [ ] Z - Level 4 - Collections! Arrays and Objects Oh My!
## Events and Callbacks
- [x] T - Level 1 - Passing functions to functions - #3 
- [x] T - Level 2 - setTimeout and setInterval - #5 
- [ ] T - Level 3 - Publish and Subscribe (hey here's a [gif to use](http://i.imgur.com/nUh850W.gif))
- [ ] Level 4 - Understanding `this`
## Interacting with the User
- [x] T - Level 1 - Collecting input from the command line - #4 
- [ ] T - Level 2 - Finding and changing elements on a web page [*prioritize] - #7 & #8 
- [ ] Level 3 - Getting data from a form
- [ ] Level 4 - Responding to user interactions
